### ISSUE TITLE
Explainability Service

### ISSUE THREAD

**Issue by ThePrecious** [ThePrecious/XRay_Prediction_and_Explainability#3]
- [x] Read https://mlmed.org/gifsplanation/
- [x] Read https://arxiv.org/abs/1910.00199
- [x] Perform surgery on existing models and find attribution maps that lead the model to predict the label that it predicted. It could be a series of attribute maps that can be made into a gif

**Comment by ashegde** [comment]
I've uploaded a notebook illustrating these methods. I'm working on integrating this into the gradio app as well.
